### ISSUE TITLE
Having battery alert 

### ISSUE THREAD

**Issue by aliakbar-bsr** [meichthys/window_sensors#4]
Hi 
Im interested in your code while it's esphome based 
is there any way like the hookup to have alert on battery ending power to know that we have to replace it ?

**Comment by meichthys** [comment]
@aliakbar-bsr Yes, there is a way to have a battery voltage level reported. Here's an example that replaces MQTT and uses the Home Assistant API to report the battery voltage as well as the sensor on/off status. Note, that in order to create an alert to replace the battery you would need to do more than just report the voltage, you would want to create an automation in Home Assistant that sends a push notification to your phone once the Voltage is reported to be below a certain amount.

```
esphome:
  name: <name of device in esphome>
  platform: ESP8266
  board: esp12e

wifi:
  ssid: "Your Wifi Name here"
  password: "Your Wifi password here"
  fast_connect: true
  power_save_mode: high
# static ip is recommended to improve connection times
  manual_ip:
    static_ip: <static_ip_of_sensor>
    gateway: <gateway ip>
    subnet: 255.255.255.0
    dns1: <dns_server_ip>

binary_sensor:
  platform: status
  name: <name of on/off sensor>
  device_class: window

#  report battery voltage
sensor:
  platform: adc
  pin: VCC
  name: <name of voltage sensor>

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over the air updates
ota:

```
